name: New Development v2
description: Use this template for creating new issues for development tasks.
title: '[Developement objective - describe your development in less than 50 words]'
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Provide a detailed description of the new development task. Also, mention the tentative release.
    validations:
      required: true

  - type: textarea
    id: mocks
    attributes:
      label: MOCKs/Screenshots
      description: Please add any screenshots/MOCKs that are available for this development
    validations:
      required: true

  - type: textarea
    id: access-patterns
    attributes:
      label: Access Patterns
      description: Describe how the user will access this feature
      placeholder: |
        1. Login as student/teacher/admin
        2. Open dashboard
        3. [and so on...]
    validations:
      required: true

  - type: textarea
    id: creds
    attributes:
      label: Sample credentials
      description: Provide some test users
      placeholder: |
        1. [User1]
        2. [User2]
    validations:
      required: true

  - type: textarea
    id: affected-pages
    attributes:
      label: Affected user pages
      description: List of pages which are being introduced/modified/deleted as part of this
    validations:
      required: true

  - type: textarea
    id: affected-apis
    attributes:
      label: Affected API routes
      description: List of backend routes which are being introduced/modified/deleted as part of this
    validations:
      required: true

  - type: checkboxes
    id: issue-checklist
    attributes:
      label: Issue checklist
      description: Make sure to complete this checklist before you create this issue.
      options:
        - label: 'Added one of the following label: "new-feature", "refactoring", OR "experimental"'
          required: true
        - label: 'Added label for the APP: "Dashboard"'
          required: true
        - label: 'Added the applicable labels: "read-operation" OR "write-operation"?'
          required: true

  - type: checkboxes
    id: pre-development-checklist
    attributes:
      label: Pre-development checklist
      description: Ensure that your team has gone through the following guidelines before starting development
      options:
        - label: |
            [Coding Guidelines](https://github.com/comprodls/c1-2024/wiki/2.-Coding-Guidelines)
          required: true
        - label: |
            [GIT Branching and Guidelines](https://github.com/comprodls/c1-2024/wiki/4.-GIT-Branching-and-Guidelines)
          required: true
        - label: |
            [Code quality and security](https://github.com/comprodls/c1-2024/wiki/3.-Code-Quality-and-Security) guidelines
          required: true
        - label: |
            [Page load performance](https://github.com/comprodls/c1-2024/wiki/5.-Page-load-Performance) guidelines
          required: true
        - label: |
            [Minimal Accessibility Checklist](https://github.com/comprodls/c1-2024/wiki/Minimal-Accessibility-Checklist)
          required: true

  - type: checkboxes
    id: post-development-checklist
    attributes:
      label: Post-development checklist
      description: Make sure to complete this checklist before you close this issue.
      options:
        - label: 'Have you run WPT tests?'
        - label: 'Have you done the QID updates as required?'
        - label: 'Have you updated the API test cases as required?'
        - label: 'Have you added your routes to OpenTelemetry for performance monitoring?'
        - label: 'Have you checked your updates for vulnerabilities?'
        - label: 'Have you checked your updates for Sonar Issues?'
        - label: 'Have you made sure that the code is following the [Minimal Accessibility guidelines](https://github.com/comprodls/c1-2024/wiki/Minimal-Accessibility-Checklist)?'

  - type: dropdown
    id: new-entities
    attributes:
      label: Are you introducing new entities or value object(s)?
      options:
        - ✅ Yes. Provide more details after creating the issue
        - ❌ No

  - type: dropdown
    id: new-projectors
    attributes:
      label: Are you introducing new projector(s) and read model(s)?
      options:
        - ✅ Yes. Provide more details after creating the issue
        - ❌ No

  - type: dropdown
    id: new-commands
    attributes:
      label: Are you introducing new command(s), command-result(s) and relevant domain service(s)??
      options:
        - ✅ Yes. Provide more details after creating the issue
        - ❌ No

  - type: dropdown
    id: new-mappers
    attributes:
      label: Are you introducing new mapper(s)?
      options:
        - ✅ Yes. Provide more details after creating the issue
        - ❌ No

  - type: dropdown
    id: new-repositories
    attributes:
      label: Are you introducing new repository(s)?
      options:
        - ✅ Yes. Provide more details after creating the issue and the reason why can't you use the existing ones?
        - ❌ No

  - type: dropdown
    id: new-composables
    attributes:
      label: Are you introducing new composable(s)?
      options:
        - ✅ Yes. Provide more details after creating the issue and justify why you it is needed?
        - ❌ No

  - type: dropdown
    id: modify-common-elements
    attributes:
      label: Are you updating any of the common components (Header, Footer, etc), common pages (Error.vue) OR global elements (plugins, base stylesheets, etc.)?
      options:
        - ✅ Yes. Provide more details after creating the issue and justify why you it is needed?
        - ❌ No

  - type: dropdown
    id: special-features
    attributes:
      label: Are you planning to use some special features such as Permanent cached images, sprites, etc? If yes, have you mentioned them clearly in the description?
      options:
        - ✅ Yes. Provide more details after creating the issue
        - ❌ No

  - type: dropdown
    id: wpt-tests
    attributes:
      label: Are you planning to write WPT tests for this development?
      options:
        - ✅ Yes. Provide WPT links after you have run them
        - ❌ No
